const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

class ReportGenerator {
  generatePDFReport(audit, outputPath) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 50
        });

        const stream = fs.createWriteStream(outputPath);
        doc.pipe(stream);

        // Header
        doc.fontSize(24).font('Helvetica-Bold').text('SecureChain Auditor™', { align: 'center' });
        doc.fontSize(14).font('Helvetica').text('Professional Smart Contract Audit Report', { align: 'center' });
        doc.moveDown(0.5);
        doc.fontSize(10).text(`Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
        doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke();
        doc.moveDown(1);

        // Executive Summary
        doc.fontSize(16).font('Helvetica-Bold').text('Executive Summary');
        doc.fontSize(11).font('Helvetica');
        doc.text(`Contract: ${audit.contractName}`);
        doc.text(`Chain: ${audit.chain}`);
        doc.text(`Audit Date: ${new Date(audit.createdAt).toLocaleDateString()}`);
        doc.moveDown(0.5);

        // Ratings
        doc.fontSize(12).font('Helvetica-Bold').text('Security Ratings');
        doc.fontSize(11).font('Helvetica');
        doc.text(`Pre-Audit Rating: ${audit.preAuditRating}/5 ⭐`);
        doc.text(`Post-Audit Rating: ${audit.postAuditRating}/5 ⭐`);
        doc.moveDown(1);

        // Vulnerability Summary
        const criticalCount = audit.vulnerabilities.filter(v => v.severity === 'Critical').length;
        const highCount = audit.vulnerabilities.filter(v => v.severity === 'High').length;
        const mediumCount = audit.vulnerabilities.filter(v => v.severity === 'Medium').length;
        const lowCount = audit.vulnerabilities.filter(v => v.severity === 'Low').length;

        doc.fontSize(12).font('Helvetica-Bold').text('Vulnerability Breakdown');
        doc.fontSize(11).font('Helvetica');
        doc.text(`Critical: ${criticalCount}`, { color: '#d32f2f' });
        doc.text(`High: ${highCount}`, { color: '#f57c00' });
        doc.text(`Medium: ${mediumCount}`, { color: '#fbc02d' });
        doc.text(`Low: ${lowCount}`, { color: '#388e3c' });
        doc.moveDown(1);

        // Detailed Vulnerabilities
        if (audit.vulnerabilities.length > 0) {
          doc.addPage();
          doc.fontSize(16).font('Helvetica-Bold').text('Detailed Vulnerability Analysis');
          doc.moveDown(0.5);

          audit.vulnerabilities.forEach((vuln, index) => {
            doc.fontSize(12).font('Helvetica-Bold').text(`${index + 1}. ${vuln.type.toUpperCase()}`);
            doc.fontSize(10).font('Helvetica');
            doc.text(`Severity: ${vuln.severity}`, { color: this.getSeverityColor(vuln.severity) });
            doc.text(`Location: ${vuln.location}`);
            doc.moveDown(0.3);
            doc.text('Description:');
            doc.text(vuln.description, { indent: 20 });
            doc.moveDown(0.3);
            doc.text('Vulnerable Code:');
            doc.font('Courier').fontSize(9).text(vuln.codeSnippet, { indent: 20, background: '#f5f5f5' });
            doc.moveDown(0.3);
            doc.font('Helvetica').fontSize(10).text('Remediation:');
            doc.text(vuln.remediation, { indent: 20 });
            doc.moveDown(0.3);
            doc.text('Fixed Code:');
            doc.font('Courier').fontSize(9).text(vuln.fixedCode, { indent: 20, background: '#e8f5e9' });
            doc.moveDown(0.8);
          });
        }

        // Compliance Section
        doc.addPage();
        doc.fontSize(16).font('Helvetica-Bold').text('Compliance & Standards');
        doc.fontSize(11).font('Helvetica');
        doc.text('This audit adheres to the following standards:');
        doc.list([
          'OWASP Top 10 for Blockchain',
          'Ethereum Improvement Proposals (EIPs)',
          'CertiK-inspired methodologies',
          'Industry best practices for smart contract security'
        ]);
        doc.moveDown(1);

        // Certification
        doc.fontSize(12).font('Helvetica-Bold').text('Audit Certification');
        doc.fontSize(10).font('Helvetica');
        doc.text('This report is generated by SecureChain Auditor™, an independent third-party auditor.');
        doc.text('The findings are based on automated analysis and industry-standard vulnerability detection.');
        doc.text('For regulatory or legal use, please consult with your legal team.');

        doc.end();

        stream.on('finish', () => {
          resolve(outputPath);
        });

        stream.on('error', reject);
      } catch (error) {
        reject(error);
      }
    });
  }

  getSeverityColor(severity) {
    const colors = {
      'Critical': '#d32f2f',
      'High': '#f57c00',
      'Medium': '#fbc02d',
      'Low': '#388e3c'
    };
    return colors[severity] || '#000000';
  }
}

module.exports = new ReportGenerator();
